### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by hzxa21** [hzxa21/peloton#10]
- [ ] Preserve order for the select elements in the query derived table
- [x] Hash and compare the inner SCAN correctly
- [ ] Inner table has DISTINCT
- [x] Parser support for `select * from A join B, C`, nested where and nested select
- [ ] Support explain
- [ ] Should implement ResetState() in all executor
- [ ] Subquery in having clause
- [ ] Same table alias in subquery and outer query
- [ ] Outer/Semi/Mark/Single Join
- [ ] What-if api
- [ ] Inject
- [ ] Make child_prop_deriver to be an iterator
